import { createUseStyles } from "react-jss";
export const useStyles = createUseStyles({
    container: {
      display: "flex",
      flexDirection: "column",
      alignItems: "center",
      padding: 20,
    },
    row: {
      display: "flex",
      justifyContent: "center",
      marginBottom: 20,
      gap: "5px",
    },
    card: {
      width: 235,
      height: 251,
      border: "1px solid #DFDFDF",
      borderRadius: "15px",
      backgroundColor: "#FFFFFF",
      display: "flex",
      flexDirection: "column",
      boxShadow: "0px 0px 6px 0px #0000000D",
      position: "relative",
      fontSize: "14px",
      fontWeight: 600,
      gap: "15px",
      padding: "10px",
    },
    input: {
      marginBottom: 10,
      border: "1px solid #D3D3D3",
      borderRadius: "8px",
      fontSize: "12px",
      padding: "4px 8px",
    },
    input1: {
      width: "85px",
      border: "0px",
      borderRadius: "15px",
      padding: "4px",
      color: "#000",
      fontSize: "18px",
    },
    result: {
      marginTop: 20,
      fontSize: 18,
      fontWeight: "bold",
    },
    connectorLine: {
      position: "absolute",
      height: 2,
      backgroundColor: "#007bff",
      zIndex: -1,
    },
    checkboxContainer: {
      display: "flex",
      flexDirection: "row",
      gap: "5px",
      width: "100%",
      padding: "0 10px",
      marginTop: "44px",
    },
    label: {
      backgroundColor: "#E29A2D",
      color: "#FFF",
      padding: "4px 8px",
      borderRadius: "14px",
      marginRight: "8px",
      fontSize: "12px",
    },
    outputlabel: {
      backgroundColor: "#4CAF79",
      color: "#FFF",
      padding: "4px 8px",
      borderRadius: "14px",
      marginRight: "8px",
      fontSize: "12px",
    },
    select: {
      borderRadius: "8px",
      padding: "4px 8px",
      fontSize: "12px",
      color: "#252525",
      border: "1px solid #D3D3D3",
    },
    text: {
      fontSize: "12px",
      color: "#252525",
      fontWeight: 500,
    },
    initialValueContainer: {
      display: "flex",
      flexDirection: "column-reverse",
      gap: "3px",
    },
    initialValueBox: {
      display: "flex",
      flexDirection: "row",
      border: "2px solid #FFC267",
      borderRadius: "15px",
    },
    resultValueContainer: {
      display: "flex",
      flexDirection: "column-reverse",
      gap: "3px",
    },
    resultValueBox: {
      display: "flex",
      flexDirection: "row",
      border: "2px solid #2DD179",
      borderRadius: "15px",
    },
    line: {
      opacity: "0.3",
      stroke: "#0066FF",
      strokeWidth: "7",
    },
    inputLabel: {
      fontSize: "10px",
      fontWeight: "500",
      color: "#585757",
    },
    image: {
      position: "absolute",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      pointerEvents: "none",
    },
    cardRow: {
      display: "flex",
      gap: "50px",
    },
    textType: {
      display: "flex",
      flexDirection: "column",
    },
  });